site_name: Exemplos AVR LIBC
site_favicon: img/favicon.ico

repo_url: https://github.com/Franzininho/exemplos-avr-libc

nav:
    - Primeiros passos: index.md
    - Hello, World!: 0x01_hello.md
    - Saída Digital: 0x02_saida_digital.md
    - Entrada digital: 0x03_entrada_digital.md
    - Timer0: 0x04_timer0.md
    - Timer0 interrupção: 0x05_timer0_int.md
    - Contadores: 0x06_contadores.md
    - Instrumento musical com Buzzer: 0x07_buzzer.md

theme: readthedocs



markdown_extensions:
    - admonition
